/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

/**
 *
 * @author Niall Martin x00110321
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//I got the picture of frances from her youtube channel the link is: http://www.youtube.com/watch?v=MzxMY1Pcp3o&feature=youtu.be
//The support picture on this page was found on google images the link is: http://www.actiondatatel.com/wp-content/uploads/2011/08/computer-support.jpg
public class ComputerServicesGUI extends javax.swing.JFrame {

    /**
     * Creates new form ComputerServicesGUI
     */
    public ComputerServicesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJP = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        picLbl = new javax.swing.JLabel();
        contactBtn = new javax.swing.JButton();
        jGameBtn = new javax.swing.JButton();
        hGameBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        tutorNLbl = new javax.swing.JLabel();
        fEmailLbl = new javax.swing.JLabel();
        studyBtn = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();
        numberLbl = new javax.swing.JLabel();
        csEmailLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ComputerServices");
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        backgroundJP.setBackground(new java.awt.Color(0, 255, 204));
        backgroundJP.setMaximumSize(new java.awt.Dimension(320, 480));
        backgroundJP.setMinimumSize(new java.awt.Dimension(320, 480));
        backgroundJP.setPreferredSize(new java.awt.Dimension(320, 480));

        titleLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Computer Support ");

        picLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        picLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/photo.jpg"))); // NOI18N
        picLbl.setMaximumSize(new java.awt.Dimension(320, 480));
        picLbl.setMinimumSize(new java.awt.Dimension(320, 480));

        contactBtn.setForeground(new java.awt.Color(0, 0, 204));
        contactBtn.setText("Contact us");
        contactBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        contactBtn.setMaximumSize(new java.awt.Dimension(125, 23));
        contactBtn.setMinimumSize(new java.awt.Dimension(125, 23));
        contactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBtnActionPerformed(evt);
            }
        });

        jGameBtn.setForeground(new java.awt.Color(0, 0, 204));
        jGameBtn.setText("Java Syntax Game");
        jGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGameBtnActionPerformed(evt);
            }
        });

        hGameBtn.setForeground(new java.awt.Color(0, 0, 204));
        hGameBtn.setText("HTML Syntax Game");
        hGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hGameBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(0, 255, 204));
        homeBtn.setForeground(new java.awt.Color(0, 255, 204));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.setMaximumSize(new java.awt.Dimension(75, 23));
        homeBtn.setMinimumSize(new java.awt.Dimension(75, 23));
        homeBtn.setPreferredSize(new java.awt.Dimension(75, 23));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        infoBtn.setForeground(new java.awt.Color(0, 0, 204));
        infoBtn.setText("Information");
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        tutorNLbl.setText("Frances Sheridan");

        fEmailLbl.setText("fsheridan@ncirl.ie");

        studyBtn.setForeground(new java.awt.Color(0, 0, 204));
        studyBtn.setText("Study Help");
        studyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyBtnActionPerformed(evt);
            }
        });

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/computer support03.gif"))); // NOI18N

        numberLbl.setText("01 6599260");

        csEmailLbl.setText(" computingsupport@ncirl.ie");

        javax.swing.GroupLayout backgroundJPLayout = new javax.swing.GroupLayout(backgroundJP);
        backgroundJP.setLayout(backgroundJPLayout);
        backgroundJPLayout.setHorizontalGroup(
            backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addComponent(picLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tutorNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fEmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csEmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addComponent(studyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        backgroundJPLayout.setVerticalGroup(
            backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPLayout.createSequentialGroup()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tutorNLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fEmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(csEmailLbl)
                .addGap(48, 48, 48)
                .addComponent(logoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJP, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-336)/2, (screenSize.height-519)/2, 336, 519);
    }// </editor-fold>//GEN-END:initComponents

    private void jGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGameBtnActionPerformed
        JavaQuizGUI myGUI = new JavaQuizGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jGameBtnActionPerformed

    private void hGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hGameBtnActionPerformed
        HTMLQuizGUI myGUI = new HTMLQuizGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hGameBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        StudentServicesAppGUI myGUI = new StudentServicesAppGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        InformationGUI myGUI = new InformationGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_infoBtnActionPerformed

    private void contactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBtnActionPerformed
        ContactUsGUI myGUI = new ContactUsGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactBtnActionPerformed

    private void studyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyBtnActionPerformed
        StudyHelpGUI myGUI = new StudyHelpGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerServicesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ComputerServicesGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundJP;
    private javax.swing.JButton contactBtn;
    private javax.swing.JLabel csEmailLbl;
    private javax.swing.JLabel fEmailLbl;
    private javax.swing.JButton hGameBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton infoBtn;
    private javax.swing.JButton jGameBtn;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel numberLbl;
    private javax.swing.JLabel picLbl;
    private javax.swing.JButton studyBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel tutorNLbl;
    // End of variables declaration//GEN-END:variables
}
