/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Leon Daly x12112381
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//The back button image was found on google images and edited in fireworks the link is: http://4.bp.blogspot.com/-hTRk-er3XlY/TZwLBAy9Y6I/AAAAAAAAAQA/upea2uWVG5A/s1600/back_button.jpg
public class ExamRevisionGUI extends javax.swing.JFrame {

    /**
     * Creates new form ExamRevisionGUI
     */
    public ExamRevisionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Picture = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BackjButton1 = new javax.swing.JButton();
        HomejButton2 = new javax.swing.JButton();
        examjLabel1 = new javax.swing.JLabel();
        setsjButton1 = new javax.swing.JButton();
        RelationsjButton2 = new javax.swing.JButton();
        LogicjButton3 = new javax.swing.JButton();
        CountingjButton4 = new javax.swing.JButton();
        statisjButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Picture.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maths Exam Revision");
        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setForeground(new java.awt.Color(0, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(320, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 480));

        BackjButton1.setBackground(new java.awt.Color(0, 255, 204));
        BackjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BackjButton1.setForeground(new java.awt.Color(0, 255, 204));
        BackjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        BackjButton1.setBorder(null);
        BackjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButton1ActionPerformed(evt);
            }
        });

        HomejButton2.setBackground(new java.awt.Color(0, 255, 204));
        HomejButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        HomejButton2.setForeground(new java.awt.Color(0, 255, 204));
        HomejButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        HomejButton2.setBorder(null);
        HomejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomejButton2ActionPerformed(evt);
            }
        });

        examjLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        examjLabel1.setText("Maths Exam Revision");

        setsjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setsjButton1.setForeground(new java.awt.Color(0, 0, 204));
        setsjButton1.setText("Sets");
        setsjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setsjButton1ActionPerformed(evt);
            }
        });

        RelationsjButton2.setForeground(new java.awt.Color(0, 0, 204));
        RelationsjButton2.setText("Relations & Functions");
        RelationsjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelationsjButton2ActionPerformed(evt);
            }
        });

        LogicjButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LogicjButton3.setForeground(new java.awt.Color(0, 0, 204));
        LogicjButton3.setText("Logic");
        LogicjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogicjButton3ActionPerformed(evt);
            }
        });

        CountingjButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CountingjButton4.setForeground(new java.awt.Color(0, 0, 204));
        CountingjButton4.setText("Counting");
        CountingjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountingjButton4ActionPerformed(evt);
            }
        });

        statisjButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statisjButton5.setForeground(new java.awt.Color(0, 0, 204));
        statisjButton5.setText("Statistics");
        statisjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisjButton5ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/math12.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackjButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogicjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statisjButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CountingjButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(setsjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examjLabel1))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(RelationsjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(examjLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogicjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setsjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statisjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountingjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(RelationsjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomejButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackjButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(336, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButton1ActionPerformed
        SupportOfficerGUI myGui = new SupportOfficerGUI();
        myGui.setVisible(true);
        this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_BackjButton1ActionPerformed

    private void HomejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomejButton2ActionPerformed
        StudentServicesAppGUI myGui = new StudentServicesAppGUI();
        myGui.setVisible(true); // TODO add your handling code here:
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_HomejButton2ActionPerformed

    private void statisjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisjButton5ActionPerformed
        try {
            String URL = "http://www.youtube.com/watch?v=qqOyy_NjflU";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } 
        
        catch (IOException ex) {
            Logger.getLogger(ExamRevisionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_statisjButton5ActionPerformed

    private void RelationsjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelationsjButton2ActionPerformed
        try {
            String URL = "http://www.youtube.com/watch?v=C-palvUKxsc";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } 
        
        catch (IOException ex) {
            Logger.getLogger(ExamRevisionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_RelationsjButton2ActionPerformed

    private void setsjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setsjButton1ActionPerformed
        try {
            String URL = "http://www.youtube.com/watch?v=BPcnpqrlkLE";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } 
        
        catch (IOException ex) {
            Logger.getLogger(ExamRevisionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_setsjButton1ActionPerformed

    private void LogicjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogicjButton3ActionPerformed
        try {
            String URL = "http://www.youtube.com/watch?v=xAbpWnx88v0";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } 
        
        catch (IOException ex) {
            Logger.getLogger(ExamRevisionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_LogicjButton3ActionPerformed

    private void CountingjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountingjButton4ActionPerformed
        try {
            String URL = "http://www.youtube.com/watch?v=i30d_VuolKE";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } 
        
        catch (IOException ex) {
            Logger.getLogger(ExamRevisionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_CountingjButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamRevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamRevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamRevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamRevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ExamRevisionGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackjButton1;
    private javax.swing.JButton CountingjButton4;
    private javax.swing.JButton HomejButton2;
    private javax.swing.JButton LogicjButton3;
    private javax.swing.JLabel Picture;
    private javax.swing.JButton RelationsjButton2;
    private javax.swing.JLabel examjLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton setsjButton1;
    private javax.swing.JButton statisjButton5;
    // End of variables declaration//GEN-END:variables
}
