/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

/**
 *
 * @author Peter Barry x12112631
 */
public class GroupsGui extends javax.swing.JFrame {

    /**
     * Creates new form GroupsGui
     */
    public GroupsGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTutorialsJp = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        groupTutorialsJsp = new javax.swing.JScrollPane();
        groupTutorialsTa = new javax.swing.JTextArea();
        groupTutorialsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group Tutorials");
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        groupTutorialsJp.setBackground(new java.awt.Color(0, 255, 204));
        groupTutorialsJp.setForeground(new java.awt.Color(0, 255, 204));
        groupTutorialsJp.setToolTipText("");
        groupTutorialsJp.setEnabled(false);
        groupTutorialsJp.setMaximumSize(new java.awt.Dimension(320, 480));
        groupTutorialsJp.setMinimumSize(new java.awt.Dimension(320, 480));
        groupTutorialsJp.setPreferredSize(new java.awt.Dimension(320, 480));

        homeBtn.setBackground(new java.awt.Color(0, 255, 204));
        homeBtn.setForeground(new java.awt.Color(0, 255, 204));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(0, 255, 204));
        backBtn.setForeground(new java.awt.Color(0, 255, 204));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        groupTutorialsJsp.setBackground(new java.awt.Color(0, 255, 204));
        groupTutorialsJsp.setBorder(null);
        groupTutorialsJsp.setForeground(new java.awt.Color(0, 255, 204));
        groupTutorialsJsp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        groupTutorialsJsp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        groupTutorialsTa.setEditable(false);
        groupTutorialsTa.setBackground(new java.awt.Color(0, 255, 204));
        groupTutorialsTa.setColumns(20);
        groupTutorialsTa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        groupTutorialsTa.setRows(5);
        groupTutorialsTa.setText("Group tutorials enable personal \ntutors and their tutees to get to\nknow each other and to begin \nbuilding the mutual understanding \nand trust upon which successful \npersonal tutoring depends.Students\nare more prepared to seek help from\nstaff whom they know and trust. \nTutors, too, are better prepared \nfor individual tutoring if they \nalready know their tutees from the\ngroup sessions. Everyone benefits \nfrom encouragement and support, not\njust those who require help with \nspecific difficulties. Students can\nalso be encouraged to support each\nothers' learning through appropriate\ndiscussion and mutual inquiry.");
        groupTutorialsTa.setBorder(null);
        groupTutorialsJsp.setViewportView(groupTutorialsTa);

        groupTutorialsLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        groupTutorialsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupTutorialsLbl.setText("Group Tutorials");

        javax.swing.GroupLayout groupTutorialsJpLayout = new javax.swing.GroupLayout(groupTutorialsJp);
        groupTutorialsJp.setLayout(groupTutorialsJpLayout);
        groupTutorialsJpLayout.setHorizontalGroup(
            groupTutorialsJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupTutorialsJpLayout.createSequentialGroup()
                .addGroup(groupTutorialsJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupTutorialsJpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeBtn))
                    .addGroup(groupTutorialsJpLayout.createSequentialGroup()
                        .addGroup(groupTutorialsJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groupTutorialsJpLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(groupTutorialsJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(groupTutorialsJpLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(groupTutorialsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        groupTutorialsJpLayout.setVerticalGroup(
            groupTutorialsJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupTutorialsJpLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(groupTutorialsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(groupTutorialsJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupTutorialsJpLayout.createSequentialGroup()
                        .addComponent(groupTutorialsJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupTutorialsJpLayout.createSequentialGroup()
                        .addGroup(groupTutorialsJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homeBtn)
                            .addComponent(backBtn))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupTutorialsJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupTutorialsJp, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-336)/2, (screenSize.height-519)/2, 336, 519);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LearningSupportGui myGui = new LearningSupportGui();
        myGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        StudentServicesAppGUI myGUI = new StudentServicesAppGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GroupsGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel groupTutorialsJp;
    private javax.swing.JScrollPane groupTutorialsJsp;
    private javax.swing.JLabel groupTutorialsLbl;
    private javax.swing.JTextArea groupTutorialsTa;
    private javax.swing.JButton homeBtn;
    // End of variables declaration//GEN-END:variables
}