/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

/**
 *
 * @author Peter Barry x12112631
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//The back button image was found on google images and edited in fireworks the link is: http://4.bp.blogspot.com/-hTRk-er3XlY/TZwLBAy9Y6I/AAAAAAAAAQA/upea2uWVG5A/s1600/back_button.jpg
public class IndividualHelpGui extends javax.swing.JFrame {

    /**
     * Creates new form IndividualHelpGui
     */
    public IndividualHelpGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        individualHelpJsp = new javax.swing.JScrollPane();
        individualHelpJp = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        individualHelpLbl = new javax.swing.JLabel();
        individualHelpInfoJsp = new javax.swing.JScrollPane();
        individualHelpInfoTa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Individual Help");
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        individualHelpJsp.setBackground(new java.awt.Color(0, 255, 204));
        individualHelpJsp.setBorder(null);
        individualHelpJsp.setForeground(new java.awt.Color(0, 255, 204));
        individualHelpJsp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        individualHelpJsp.setMaximumSize(new java.awt.Dimension(320, 480));
        individualHelpJsp.setMinimumSize(new java.awt.Dimension(320, 480));
        individualHelpJsp.setPreferredSize(new java.awt.Dimension(320, 480));

        individualHelpJp.setBackground(new java.awt.Color(0, 255, 204));
        individualHelpJp.setEnabled(false);
        individualHelpJp.setMaximumSize(new java.awt.Dimension(320, 690));
        individualHelpJp.setMinimumSize(new java.awt.Dimension(320, 690));
        individualHelpJp.setPreferredSize(new java.awt.Dimension(320, 690));

        backBtn.setBackground(new java.awt.Color(0, 255, 204));
        backBtn.setForeground(new java.awt.Color(0, 255, 204));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        individualHelpLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        individualHelpLbl.setText("Individual Help");

        individualHelpInfoJsp.setBorder(null);
        individualHelpInfoJsp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        individualHelpInfoJsp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        individualHelpInfoTa.setBackground(new java.awt.Color(0, 255, 204));
        individualHelpInfoTa.setColumns(20);
        individualHelpInfoTa.setEditable(false);
        individualHelpInfoTa.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        individualHelpInfoTa.setRows(5);
        individualHelpInfoTa.setText("Free one-on-one tutoring is\navailable for students who are\nexperiencing academic difficulty.\nStudents who wish to apply for\nindividual tutoring should make an\nappointment with the tutor.\n\nThis tutorial is specifically \ndesigned to meet the students\nparticular needs in areas were\nthey feel are hard to learn.\nOne to One tutorials offer the\nfastest, relevant and effective\nform of educational training.\n\nThis allows the collegeto get the\nbest out of the students and to\nhelp them succeed in their college\nstudies.\n\nPlease dont hestitate in contacting\nme as it will be in the strictest of\nconfidence.I will be only to happy \nto help you with your academic \nstudies.\n\nAsking for help is a sign of\nmaturity.\n ");
        individualHelpInfoTa.setBorder(null);
        individualHelpInfoTa.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        individualHelpInfoTa.setEnabled(false);
        individualHelpInfoTa.setSelectionColor(new java.awt.Color(51, 0, 51));
        individualHelpInfoJsp.setViewportView(individualHelpInfoTa);

        javax.swing.GroupLayout individualHelpJpLayout = new javax.swing.GroupLayout(individualHelpJp);
        individualHelpJp.setLayout(individualHelpJpLayout);
        individualHelpJpLayout.setHorizontalGroup(
            individualHelpJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(individualHelpJpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(individualHelpJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(individualHelpJpLayout.createSequentialGroup()
                        .addGroup(individualHelpJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(individualHelpJpLayout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(208, 208, 208)
                                .addComponent(homeBtn))
                            .addComponent(individualHelpInfoJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, individualHelpJpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(individualHelpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        individualHelpJpLayout.setVerticalGroup(
            individualHelpJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, individualHelpJpLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(individualHelpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(individualHelpInfoJsp, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(individualHelpJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn)
                    .addComponent(backBtn))
                .addContainerGap())
        );

        individualHelpJsp.setViewportView(individualHelpJp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(individualHelpJsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(individualHelpJsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(336, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        TopicsGui myGui = new TopicsGui();
        myGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        StudentServicesAppGUI myGui = new StudentServicesAppGUI();
        myGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualHelpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualHelpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualHelpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualHelpGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IndividualHelpGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JScrollPane individualHelpInfoJsp;
    private javax.swing.JTextArea individualHelpInfoTa;
    private javax.swing.JPanel individualHelpJp;
    private javax.swing.JScrollPane individualHelpJsp;
    private javax.swing.JLabel individualHelpLbl;
    // End of variables declaration//GEN-END:variables
}
