/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Niall Martin x00110321
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//The back button image was found on google images and edited in fireworks the link is: http://4.bp.blogspot.com/-hTRk-er3XlY/TZwLBAy9Y6I/AAAAAAAAAQA/upea2uWVG5A/s1600/back_button.jpg
public class InformationGUI extends javax.swing.JFrame {

    File myFileCalendar;

    /**
     * Creates new form InformationGUI
     */
    public InformationGUI() {
        initComponents();
        myFileCalendar = new File("..\\Group C\\src\\files\\calendar.pdf");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoJsp = new javax.swing.JScrollPane();
        infoJp = new javax.swing.JPanel();
        swatLbl = new javax.swing.JLabel();
        oTutLbl = new javax.swing.JLabel();
        cTutLbl = new javax.swing.JLabel();
        workshopLbl = new javax.swing.JLabel();
        moodleLbl = new javax.swing.JLabel();
        examLbl = new javax.swing.JLabel();
        swatJsp = new javax.swing.JScrollPane();
        swatTa = new javax.swing.JTextArea();
        oTutJsp = new javax.swing.JScrollPane();
        oTutTa = new javax.swing.JTextArea();
        cTutJsp = new javax.swing.JScrollPane();
        cTutTa = new javax.swing.JTextArea();
        workshopJsp = new javax.swing.JScrollPane();
        workshopTa = new javax.swing.JTextArea();
        moodleJsp = new javax.swing.JScrollPane();
        moodleTa = new javax.swing.JTextArea();
        examJsp = new javax.swing.JScrollPane();
        examTa = new javax.swing.JTextArea();
        moodleBtn = new javax.swing.JButton();
        workshopBtn = new javax.swing.JButton();
        wInfoBtn = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        infoTitleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information Page");
        setBackground(new java.awt.Color(0, 255, 204));
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        infoJsp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        infoJsp.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        infoJsp.setMaximumSize(new java.awt.Dimension(320, 480));
        infoJsp.setMinimumSize(new java.awt.Dimension(320, 480));
        infoJsp.setPreferredSize(new java.awt.Dimension(320, 480));
        infoJsp.setVerifyInputWhenFocusTarget(false);

        infoJp.setBackground(new java.awt.Color(0, 255, 204));
        infoJp.setMaximumSize(new java.awt.Dimension(250, 32767));
        infoJp.setMinimumSize(new java.awt.Dimension(250, 0));
        infoJp.setPreferredSize(new java.awt.Dimension(250, 1415));

        swatLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        swatLbl.setText("SWAT Workshops");

        oTutLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        oTutLbl.setText("1 to 1 & Small Group Tutorials");

        cTutLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        cTutLbl.setText("Whole Class Tutorials");

        workshopLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        workshopLbl.setText("Drop In Workshops");

        moodleLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        moodleLbl.setText("Moodle");

        examLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 16)); // NOI18N
        examLbl.setText("Exam Revision");

        swatJsp.setBorder(null);
        swatJsp.setOpaque(false);

        swatTa.setEditable(false);
        swatTa.setBackground(new java.awt.Color(0, 255, 204));
        swatTa.setColumns(20);
        swatTa.setForeground(new java.awt.Color(51, 51, 51));
        swatTa.setRows(5);
        swatTa.setText(" In semester one the Computing Support\n Service runs a series of workshops\n for first year students focussing on\n the skills needed when settling into\n a new college course. These include\n topics such as, touch typing,referencing,\n research etc. These sessions are not\n mandatory but attendance is strongly\n recommended.");
        swatTa.setBorder(null);
        swatTa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        swatTa.setNextFocusableComponent(this);
        swatJsp.setViewportView(swatTa);

        oTutJsp.setBorder(null);

        oTutTa.setEditable(false);
        oTutTa.setBackground(new java.awt.Color(0, 255, 204));
        oTutTa.setColumns(20);
        oTutTa.setRows(5);
        oTutTa.setText(" The Computing Support Tutor is available to\n work with students on a one to one or small\n group basis. Students that find that they are\n falling behind in a module or that are finding\n a particular topic difficult to understand\n should contact the Support Tutor for an\n appointment and get caught up before it\n becomes a problem.To make an appointment\n email computingsupport@ncirl.ie with a\n suggested time that you are free to meet.");
        oTutTa.setBorder(null);
        oTutJsp.setViewportView(oTutTa);

        cTutJsp.setBorder(null);

        cTutTa.setEditable(false);
        cTutTa.setBackground(new java.awt.Color(0, 255, 204));
        cTutTa.setColumns(20);
        cTutTa.setRows(5);
        cTutTa.setText(" If a class are finding a particular module or\n topic difficult and need an additional tutorial,\n the lecturer or class rep may contact the Support\n Tutor who will then schedule an extra tutorial for\n the whole class.");
        cTutTa.setBorder(null);
        cTutJsp.setViewportView(cTutTa);

        workshopJsp.setBorder(null);

        workshopTa.setEditable(false);
        workshopTa.setBackground(new java.awt.Color(0, 255, 204));
        workshopTa.setColumns(20);
        workshopTa.setRows(5);
        workshopTa.setText(" The Computing Support Service runs weekly\n support workshops for first year students\n in Computer Programming. These sessions\n are scheduled in your timetable from week 3\n or 4 onwards.If you have a small question or\n query you can always just pop into the\n session and ask or you might simply come\n along and use the time to work on\n additional programmes or project work with\n the support of the tutor.No appointment\n needed! Where additional tutorials on\n particular topics are requested,the workshops\n can also be used as an additional tutorial\n session instead.");
        workshopTa.setBorder(null);
        workshopJsp.setViewportView(workshopTa);

        moodleJsp.setBorder(null);

        moodleTa.setEditable(false);
        moodleTa.setBackground(new java.awt.Color(0, 255, 204));
        moodleTa.setColumns(20);
        moodleTa.setRows(5);
        moodleTa.setText(" The Computing Support Service also has a\n Moodle page where you can find a schedule\n of extra classes and Drop in Workshop hours\n as well as past exam papers and revision\n material for some modules.Enrol yourself on\n the Computing Support Moodle page by\n clicking the moodle button below.");
        moodleTa.setBorder(null);
        moodleJsp.setViewportView(moodleTa);

        examJsp.setBorder(null);

        examTa.setEditable(false);
        examTa.setBackground(new java.awt.Color(0, 255, 204));
        examTa.setColumns(20);
        examTa.setRows(5);
        examTa.setText(" Exam revision sessions will be held in the\n run up to each exam session. These sessions\n will take you through past or sample exam\n questions and solutions in preparation for\n the exams.");
        examTa.setBorder(null);
        examJsp.setViewportView(examTa);

        moodleBtn.setForeground(new java.awt.Color(0, 0, 204));
        moodleBtn.setText("Moodle");
        moodleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodleBtnActionPerformed(evt);
            }
        });

        workshopBtn.setForeground(new java.awt.Color(0, 0, 204));
        workshopBtn.setText("Workshops");
        workshopBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        workshopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopBtnActionPerformed(evt);
            }
        });

        wInfoBtn.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        wInfoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wInfoBtn.setText("Link to view workshop times");

        backBtn.setBackground(new java.awt.Color(0, 255, 204));
        backBtn.setForeground(new java.awt.Color(0, 255, 204));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(0, 255, 204));
        homeBtn.setForeground(new java.awt.Color(0, 255, 204));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        infoTitleLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        infoTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoTitleLbl.setText("Information Page");

        javax.swing.GroupLayout infoJpLayout = new javax.swing.GroupLayout(infoJp);
        infoJp.setLayout(infoJpLayout);
        infoJpLayout.setHorizontalGroup(
            infoJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJpLayout.createSequentialGroup()
                .addGroup(infoJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoJpLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(infoJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workshopBtn)
                            .addComponent(moodleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(infoJpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(infoJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moodleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wInfoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(workshopJsp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cTutLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cTutJsp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(swatJsp)
                            .addComponent(swatLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oTutJsp)
                            .addComponent(oTutLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(moodleJsp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(examLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(examJsp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(infoJpLayout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homeBtn))
                            .addGroup(infoJpLayout.createSequentialGroup()
                                .addComponent(workshopLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        infoJpLayout.setVerticalGroup(
            infoJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoTitleLbl)
                .addGap(18, 18, 18)
                .addComponent(swatLbl)
                .addGap(18, 18, 18)
                .addComponent(swatJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oTutLbl)
                .addGap(18, 18, 18)
                .addComponent(oTutJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cTutLbl)
                .addGap(18, 18, 18)
                .addComponent(cTutJsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(workshopLbl)
                .addGap(18, 18, 18)
                .addComponent(workshopJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wInfoBtn)
                .addGap(18, 18, 18)
                .addComponent(workshopBtn)
                .addGap(18, 18, 18)
                .addComponent(moodleLbl)
                .addGap(18, 18, 18)
                .addComponent(moodleJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moodleBtn)
                .addGap(18, 18, 18)
                .addComponent(examLbl)
                .addGap(18, 18, 18)
                .addComponent(examJsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(infoJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(homeBtn))
                .addContainerGap(5, Short.MAX_VALUE))
        );

        infoJsp.setViewportView(infoJp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoJsp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoJsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(336, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moodleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodleBtnActionPerformed
        //Links to the computer support page on moodle
        //I got this code from the project fourm
        try {
            String URL = "https://moodle.ncirl.ie/course/view.php?id=1199";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } 
        
        catch (IOException ex) {
            Logger.getLogger(ComputerServicesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_moodleBtnActionPerformed

    private void workshopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopBtnActionPerformed
        //This code is to open a pdf file.
        //i.e I got some of this code from the stackoverflow website:
        if (myFileCalendar.toString().endsWith(".pdf")) {


            try {
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + myFileCalendar);
            } 
            
            catch (IOException ex) {
                Logger.getLogger(InformationGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        
        else {
            Desktop desktop = Desktop.getDesktop();

            try {
                desktop.open(myFileCalendar);
            } 
            
            catch (IOException ex) {
                Logger.getLogger(InformationGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_workshopBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ComputerServicesGUI myGUI = new ComputerServicesGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        StudentServicesAppGUI myGUI = new StudentServicesAppGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InformationGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane cTutJsp;
    private javax.swing.JLabel cTutLbl;
    private javax.swing.JTextArea cTutTa;
    private javax.swing.JScrollPane examJsp;
    private javax.swing.JLabel examLbl;
    private javax.swing.JTextArea examTa;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel infoJp;
    private javax.swing.JScrollPane infoJsp;
    private javax.swing.JLabel infoTitleLbl;
    private javax.swing.JButton moodleBtn;
    private javax.swing.JScrollPane moodleJsp;
    private javax.swing.JLabel moodleLbl;
    private javax.swing.JTextArea moodleTa;
    private javax.swing.JScrollPane oTutJsp;
    private javax.swing.JLabel oTutLbl;
    private javax.swing.JTextArea oTutTa;
    private javax.swing.JScrollPane swatJsp;
    private javax.swing.JLabel swatLbl;
    private javax.swing.JTextArea swatTa;
    private javax.swing.JLabel wInfoBtn;
    private javax.swing.JButton workshopBtn;
    private javax.swing.JScrollPane workshopJsp;
    private javax.swing.JLabel workshopLbl;
    private javax.swing.JTextArea workshopTa;
    // End of variables declaration//GEN-END:variables
}