/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Niall Martin x00110321
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//The back button image was found on google images and edited in fireworks the link is: http://4.bp.blogspot.com/-hTRk-er3XlY/TZwLBAy9Y6I/AAAAAAAAAQA/upea2uWVG5A/s1600/back_button.jpg
public class JavaQuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form JavaQuizGUI
     */
    public JavaQuizGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question1Bg = new javax.swing.ButtonGroup();
        question2Bg = new javax.swing.ButtonGroup();
        question3Rg = new javax.swing.ButtonGroup();
        javaQuizJp = new javax.swing.JPanel();
        javaQTLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        q1Lbl = new javax.swing.JLabel();
        q1ARb = new javax.swing.JRadioButton();
        q1BRb = new javax.swing.JRadioButton();
        q1CRb = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        q2Lbl = new javax.swing.JLabel();
        q2ARb = new javax.swing.JRadioButton();
        q2BRb = new javax.swing.JRadioButton();
        q2CRb = new javax.swing.JRadioButton();
        q3Lbl = new javax.swing.JLabel();
        q3ARb = new javax.swing.JRadioButton();
        q3BRb = new javax.swing.JRadioButton();
        q3CRb = new javax.swing.JRadioButton();
        q3BLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JAVA QUIZ");
        setBackground(new java.awt.Color(0, 255, 204));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        javaQuizJp.setBackground(new java.awt.Color(0, 255, 204));
        javaQuizJp.setMaximumSize(new java.awt.Dimension(320, 480));
        javaQuizJp.setMinimumSize(new java.awt.Dimension(320, 480));
        javaQuizJp.setPreferredSize(new java.awt.Dimension(320, 480));

        javaQTLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        javaQTLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaQTLbl.setText("JAVA QUIZ");

        backBtn.setBackground(new java.awt.Color(0, 255, 204));
        backBtn.setForeground(new java.awt.Color(0, 255, 204));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(0, 255, 204));
        homeBtn.setForeground(new java.awt.Color(0, 255, 204));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        q1Lbl.setText("Q1.  How many ActionListeners can listen to a control?");

        question1Bg.add(q1ARb);
        q1ARb.setText("a. As many as you like ");
        q1ARb.setOpaque(false);

        question1Bg.add(q1BRb);
        q1BRb.setText("b. Exactly 1 ");
        q1BRb.setOpaque(false);

        question1Bg.add(q1CRb);
        q1CRb.setText("c. None ");
        q1CRb.setOpaque(false);

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        q2Lbl.setText("Q2.  What is a callback in swing?");

        question2Bg.add(q2ARb);
        q2ARb.setText("a. A control notifies an action listener ");
        q2ARb.setOpaque(false);

        question2Bg.add(q2BRb);
        q2BRb.setText("b. A button calls a specified phone number ");
        q2BRb.setOpaque(false);
        q2BRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2BRbActionPerformed(evt);
            }
        });

        question2Bg.add(q2CRb);
        q2CRb.setText("c. An object is clicked or changed ");
        q2CRb.setOpaque(false);

        q3Lbl.setText("Q3. Which of the following is the import code for");

        question3Rg.add(q3ARb);
        q3ARb.setText("a. import java.util.Array;");
        q3ARb.setOpaque(false);

        question3Rg.add(q3BRb);
        q3BRb.setText("b. import java.swing.ArrayList;");
        q3BRb.setOpaque(false);

        question3Rg.add(q3CRb);
        q3CRb.setText("c. import java.util.ArrayList;");
        q3CRb.setOpaque(false);

        q3BLbl.setText(" an ArrayList?");

        javax.swing.GroupLayout javaQuizJpLayout = new javax.swing.GroupLayout(javaQuizJp);
        javaQuizJp.setLayout(javaQuizJpLayout);
        javaQuizJpLayout.setHorizontalGroup(
            javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(javaQTLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javaQuizJpLayout.createSequentialGroup()
                .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javaQuizJpLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1BRb)
                            .addComponent(q1ARb)
                            .addComponent(q1CRb)))
                    .addGroup(javaQuizJpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2BRb)
                            .addComponent(q2ARb)
                            .addComponent(q2CRb))))
                .addGap(0, 59, Short.MAX_VALUE))
            .addGroup(javaQuizJpLayout.createSequentialGroup()
                .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, javaQuizJpLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(backBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, javaQuizJpLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q2Lbl)
                                .addComponent(q1Lbl)
                                .addComponent(q3Lbl)
                                .addComponent(q3BLbl))))
                    .addGroup(javaQuizJpLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q3ARb)
                            .addComponent(q3CRb)
                            .addComponent(q3BRb)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        javaQuizJpLayout.setVerticalGroup(
            javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javaQuizJpLayout.createSequentialGroup()
                .addComponent(javaQTLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q1ARb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q1BRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q1CRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q2ARb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q2BRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q2CRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q3Lbl)
                .addGap(11, 11, 11)
                .addComponent(q3BLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q3ARb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q3BRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q3CRb)
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(javaQuizJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn)
                    .addComponent(backBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(javaQuizJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(javaQuizJp, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-336)/2, (screenSize.height-519)/2, 336, 519);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        StudentServicesAppGUI myGUI = new StudentServicesAppGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ComputerServicesGUI myGUI = new ComputerServicesGUI();
        myGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        //If statement for java quiz        
        if (q1ARb.isSelected() && q2ARb.isSelected() && q3CRb.isSelected()) {
            JOptionPane.showMessageDialog(null, "Well Done" + "\n" + " You answered all right");
        } 
        
        else if (q1ARb.isSelected() && q2ARb.isSelected() && q3ARb.isSelected()
                || q1ARb.isSelected() && q2ARb.isSelected() && q3BRb.isSelected()
                || q1BRb.isSelected() && q2ARb.isSelected() && q3CRb.isSelected()
                || q1ARb.isSelected() && q2BRb.isSelected() && q3CRb.isSelected()
                || q1CRb.isSelected() && q2ARb.isSelected() && q3CRb.isSelected()
                || q1ARb.isSelected() && q2CRb.isSelected() && q3CRb.isSelected()) {

            JOptionPane.showMessageDialog(null, "You got 2 out of 3 right");
        } 
        
        else if (q1ARb.isSelected() && q2BRb.isSelected() && q3ARb.isSelected()
                || q1ARb.isSelected() && q2BRb.isSelected() && q3BRb.isSelected()
                || q1ARb.isSelected() && q2CRb.isSelected() && q3ARb.isSelected()
                || q1ARb.isSelected() && q2CRb.isSelected() && q3BRb.isSelected()
                || q1BRb.isSelected() && q2ARb.isSelected() && q3ARb.isSelected()
                || q1BRb.isSelected() && q2ARb.isSelected() && q3BRb.isSelected()
                || q1CRb.isSelected() && q2ARb.isSelected() && q3ARb.isSelected()
                || q1CRb.isSelected() && q2ARb.isSelected() && q3BRb.isSelected()
                || q1BRb.isSelected() && q2BRb.isSelected() && q3CRb.isSelected()
                || q1CRb.isSelected() && q2BRb.isSelected() && q3CRb.isSelected()
                || q1CRb.isSelected() && q2CRb.isSelected() && q3CRb.isSelected()
                || q1BRb.isSelected() && q2CRb.isSelected() && q3CRb.isSelected()) {

            JOptionPane.showMessageDialog(null, "You only got 1 question right");
        } 
        
        else {
            JOptionPane.showMessageDialog(null, "Un Lucky" + "\n" + "You answered all questions  wrong");
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void q2BRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2BRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2BRbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JavaQuizGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel javaQTLbl;
    private javax.swing.JPanel javaQuizJp;
    private javax.swing.JRadioButton q1ARb;
    private javax.swing.JRadioButton q1BRb;
    private javax.swing.JRadioButton q1CRb;
    private javax.swing.JLabel q1Lbl;
    private javax.swing.JRadioButton q2ARb;
    private javax.swing.JRadioButton q2BRb;
    private javax.swing.JRadioButton q2CRb;
    private javax.swing.JLabel q2Lbl;
    private javax.swing.JRadioButton q3ARb;
    private javax.swing.JLabel q3BLbl;
    private javax.swing.JRadioButton q3BRb;
    private javax.swing.JRadioButton q3CRb;
    private javax.swing.JLabel q3Lbl;
    private javax.swing.ButtonGroup question1Bg;
    private javax.swing.ButtonGroup question2Bg;
    private javax.swing.ButtonGroup question3Rg;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
