/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

/**
 *
 * @author Leon Daly x12112381
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//The back button image was found on google images and edited in fireworks the link is: http://4.bp.blogspot.com/-hTRk-er3XlY/TZwLBAy9Y6I/AAAAAAAAAQA/upea2uWVG5A/s1600/back_button.jpg
public class mathsGui extends javax.swing.JFrame {

    /**
     * Creates new form mathsGui
     */
    public maths maths;

    public mathsGui() {
        initComponents();
        maths = new maths();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundJP = new javax.swing.JPanel();
        num1JL = new javax.swing.JLabel();
        num2Jl = new javax.swing.JLabel();
        num1TF = new javax.swing.JTextField();
        num2TF = new javax.swing.JTextField();
        ansJL = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Subtract = new javax.swing.JButton();
        Officer = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        BackjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        backgroundJP.setBackground(new java.awt.Color(0, 255, 204));
        backgroundJP.setForeground(new java.awt.Color(0, 255, 204));
        backgroundJP.setMaximumSize(new java.awt.Dimension(320, 480));
        backgroundJP.setMinimumSize(new java.awt.Dimension(320, 480));
        backgroundJP.setPreferredSize(new java.awt.Dimension(320, 480));

        num1JL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num1JL.setText("Enter Number");

        num2Jl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num2Jl.setText("Enter Number");

        num1TF.setBackground(new java.awt.Color(153, 255, 204));
        num1TF.setForeground(new java.awt.Color(0, 0, 255));
        num1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1TFActionPerformed(evt);
            }
        });

        num2TF.setBackground(new java.awt.Color(153, 255, 204));
        num2TF.setForeground(new java.awt.Color(0, 0, 204));
        num2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2TFActionPerformed(evt);
            }
        });

        ADD.setForeground(new java.awt.Color(0, 0, 204));
        ADD.setText("Add");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        multiply.setForeground(new java.awt.Color(0, 0, 204));
        multiply.setText("Multiply");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        Divide.setForeground(new java.awt.Color(0, 0, 204));
        Divide.setText("Divide");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });

        Subtract.setForeground(new java.awt.Color(0, 0, 204));
        Subtract.setText("Subtract");
        Subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractActionPerformed(evt);
            }
        });

        Officer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Officer.setForeground(new java.awt.Color(0, 0, 204));
        Officer.setText("Goto Support Officer Page");
        Officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficerActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(0, 255, 204));
        Home.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 255, 204));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        Home.setBorder(null);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        BackjButton1.setBackground(new java.awt.Color(0, 255, 204));
        BackjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BackjButton1.setForeground(new java.awt.Color(0, 255, 204));
        BackjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        BackjButton1.setBorder(null);
        BackjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundJPLayout = new javax.swing.GroupLayout(backgroundJP);
        backgroundJP.setLayout(backgroundJPLayout);
        backgroundJPLayout.setHorizontalGroup(
            backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundJPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ansJL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(backgroundJPLayout.createSequentialGroup()
                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Home))
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundJPLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(num1TF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(num2TF, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(backgroundJPLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(num2Jl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(num1JL, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(backgroundJPLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Officer, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundJPLayout.setVerticalGroup(
            backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundJPLayout.createSequentialGroup()
                .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Officer)
                        .addGap(47, 47, 47)
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1JL))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num2Jl)
                            .addComponent(num2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ansJL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(BackjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundJPLayout.createSequentialGroup()
                        .addContainerGap(429, Short.MAX_VALUE)
                        .addComponent(Home)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(336, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void num2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2TFActionPerformed

    private void num1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1TFActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        int num1, num2, ans;

        num1 = Integer.parseInt(num1TF.getText());
        num2 = Integer.parseInt(num2TF.getText());

        maths.setNum1(num1);
        maths.setNum2(num2);

        maths.add();


        ans = maths.getAns();


        ansJL.setText("Answer = " + ans);
    }//GEN-LAST:event_ADDActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        int num1, num2, ans;

        num1 = Integer.parseInt(num1TF.getText());
        num2 = Integer.parseInt(num2TF.getText());

        maths.setNum1(num1);
        maths.setNum2(num2);

        maths.multiply();


        ans = maths.getAns();


        ansJL.setText("Answer = " + ans);
    }//GEN-LAST:event_multiplyActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        int num1, num2, ans;

        num1 = Integer.parseInt(num1TF.getText());
        num2 = Integer.parseInt(num2TF.getText());

        maths.setNum1(num1);
        maths.setNum2(num2);

        maths.Divide();


        ans = maths.getAns();


        ansJL.setText("Answer = " + ans);       
    }//GEN-LAST:event_DivideActionPerformed

    private void SubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractActionPerformed
        int num1, num2, ans;

        num1 = Integer.parseInt(num1TF.getText());
        num2 = Integer.parseInt(num2TF.getText());

        maths.setNum1(num1);
        maths.setNum2(num2);

        maths.Subtract();


        ans = maths.getAns();


        ansJL.setText("Answer =  " + ans);   
    }//GEN-LAST:event_SubtractActionPerformed

    private void OfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficerActionPerformed
        SupportOfficerGUI myGui = new SupportOfficerGUI();
        myGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OfficerActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        StudentServicesAppGUI myGui = new StudentServicesAppGUI();
        myGui.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_HomeActionPerformed

    private void BackjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButton1ActionPerformed
        SupportOfficerGUI myGui = new SupportOfficerGUI();
        myGui.setVisible(true); 
        this.setVisible(false);  
    }//GEN-LAST:event_BackjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mathsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mathsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mathsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mathsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mathsGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton BackjButton1;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Home;
    private javax.swing.JButton Officer;
    private javax.swing.JButton Subtract;
    private javax.swing.JLabel ansJL;
    private javax.swing.JPanel backgroundJP;
    private javax.swing.JButton multiply;
    private javax.swing.JLabel num1JL;
    private javax.swing.JTextField num1TF;
    private javax.swing.JLabel num2Jl;
    private javax.swing.JTextField num2TF;
    // End of variables declaration//GEN-END:variables
}
