/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

import StudentServicesApp.OneToOne;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * @author Leon Daly x12112381
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//The back button image was found on google images and edited in fireworks the link is: http://4.bp.blogspot.com/-hTRk-er3XlY/TZwLBAy9Y6I/AAAAAAAAAQA/upea2uWVG5A/s1600/back_button.jpg
public class OneToOneGUI extends javax.swing.JFrame {

    private ArrayList<OneToOne> aList;
    private String name1;
    private String surname;
    private String email1;
    private String areaofhelp1;
    
    //declare array of Question objects
    private OneToOne oArray[];
    
    //declare count variable to keep track of how many objects are in array
    private int count;

    /**
     * Creates new form OneToOneGUI
     */
    public OneToOneGUI() {
        initComponents();

        name1 = new String();
        surname = new String();
        email1 = new String();
        areaofhelp1 = new String();
        //create array of question objects
        aList = new ArrayList<>();
        //initialise count to 0
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oneToOnePageJp = new javax.swing.JPanel();
        onetoone = new javax.swing.JLabel();
        Surname1 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        surnametf = new javax.swing.JTextField();
        emailtf = new javax.swing.JTextField();
        areaofhelptf = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        displaybtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        areaofhelp = new javax.swing.JLabel();
        savetf = new javax.swing.JButton();
        readtf = new javax.swing.JButton();
        Searchtf = new javax.swing.JButton();
        Deletetf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("One To One Page");
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        oneToOnePageJp.setBackground(new java.awt.Color(0, 255, 204));
        oneToOnePageJp.setForeground(new java.awt.Color(0, 0, 204));
        oneToOnePageJp.setMaximumSize(new java.awt.Dimension(320, 480));
        oneToOnePageJp.setMinimumSize(new java.awt.Dimension(320, 480));
        oneToOnePageJp.setPreferredSize(new java.awt.Dimension(320, 480));

        onetoone.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        onetoone.setText("OneToOne Page");

        Surname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Surname1.setText("Surname :");

        areaofhelptf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaofhelptfActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(0, 0, 204));
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        displaybtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displaybtn.setForeground(new java.awt.Color(0, 0, 204));
        displaybtn.setText("Display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addbtn.setForeground(new java.awt.Color(0, 0, 204));
        addbtn.setText("Submit Details");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        homebtn.setBackground(new java.awt.Color(0, 255, 204));
        homebtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        homebtn.setForeground(new java.awt.Color(0, 255, 204));
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        homebtn.setBorder(null);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(0, 255, 204));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 255, 204));
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText(" Name :");

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setText("Email :");

        areaofhelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        areaofhelp.setText("Area of Help :");

        savetf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        savetf.setForeground(new java.awt.Color(0, 0, 204));
        savetf.setText("Save To File");
        savetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetfActionPerformed(evt);
            }
        });

        readtf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        readtf.setForeground(new java.awt.Color(0, 0, 204));
        readtf.setText("View Saved File");
        readtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readtfActionPerformed(evt);
            }
        });

        Searchtf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Searchtf.setForeground(new java.awt.Color(0, 0, 204));
        Searchtf.setText("Search File");
        Searchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchtfActionPerformed(evt);
            }
        });

        Deletetf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Deletetf.setForeground(new java.awt.Color(0, 0, 204));
        Deletetf.setText("Delete File");
        Deletetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletetfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout oneToOnePageJpLayout = new javax.swing.GroupLayout(oneToOnePageJp);
        oneToOnePageJp.setLayout(oneToOnePageJpLayout);
        oneToOnePageJpLayout.setHorizontalGroup(
            oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneToOnePageJpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oneToOnePageJpLayout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homebtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oneToOnePageJpLayout.createSequentialGroup()
                        .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Searchtf, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(Deletetf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(readtf, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(savetf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displaybtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oneToOnePageJpLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaofhelp)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Surname1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailtf)
                    .addComponent(areaofhelptf)
                    .addGroup(oneToOnePageJpLayout.createSequentialGroup()
                        .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap(23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oneToOnePageJpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(onetoone, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        oneToOnePageJpLayout.setVerticalGroup(
            oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneToOnePageJpLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(onetoone)
                .addGap(31, 31, 31)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Surname1)
                    .addComponent(surnametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email))
                .addGap(18, 18, 18)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaofhelptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaofhelp))
                .addGap(29, 29, 29)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displaybtn)
                    .addComponent(clearbtn))
                .addGap(18, 18, 18)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchtf)
                    .addComponent(savetf))
                .addGap(18, 18, 18)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletetf)
                    .addComponent(readtf))
                .addGap(18, 18, 18)
                .addGroup(oneToOnePageJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homebtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oneToOnePageJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oneToOnePageJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(336, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        nametf.setText("");
        surnametf.setText("");
        emailtf.setText("");
        areaofhelptf.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        StudentServicesAppGUI myGui = new StudentServicesAppGUI();
        myGui.setVisible(true); 
        this.setVisible(false);  
    }//GEN-LAST:event_homebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        SupportOfficerGUI myGui = new SupportOfficerGUI();
        myGui.setVisible(true); 
        this.setVisible(false);  
    }//GEN-LAST:event_backbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        name1 = nametf.getText();
        surname = surnametf.getText();
        email1 = emailtf.getText();
        areaofhelp1 = areaofhelptf.getText();

        //create a new Question object
        OneToOne o = new OneToOne();

        //add contents of textfields to q
        o.setName(name1);
        o.setSurname(surname);
        o.setEmail(email1);
        o.setAreaofhelp(areaofhelp1);

        //add q to array of Question objects
        aList.add(o);
        //increase count to show that another object has been added to the array
        count++;
    }//GEN-LAST:event_addbtnActionPerformed

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(null,
                    "Name : " + "" + aList.get(i).getName()
                    + "\n Surname: " + "" + aList.get(i).getSurname()
                    + "\n Email: " + "" + aList.get(i).getEmail()
                    + "\n Area of Help : " + "" + aList.get(i).getAreaofhelp());

        }
    }//GEN-LAST:event_displaybtnActionPerformed

    private void areaofhelptfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaofhelptfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaofhelptfActionPerformed

    private void savetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetfActionPerformed
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(aList);

            JOptionPane.showMessageDialog(null, "Form Saved Sucessfully");

            oStream.close();


        } 
        
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_savetfActionPerformed

    private void readtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readtfActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            ArrayList<OneToOne> oList;
            oList = (ArrayList<OneToOne>) oStream.readObject();

            for (OneToOne o : oList) {
                JOptionPane.showMessageDialog(null, "Name: " + o.getName() + " \n Surname: " + o.getSurname() + " \n Email: " + o.getEmail() + " \nAreaofhelp: " + o.getAreaofhelp());
            }
            oStream.close();
        } 
        
        catch (IOException e) {
            System.out.print(e);
        } 
        
        catch (ClassNotFoundException ex) {
            System.out.print(ex);
        }
    }//GEN-LAST:event_readtfActionPerformed

    private void SearchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchtfActionPerformed
        String searchType = JOptionPane.showInputDialog(null, "Please enter the type you wish to search for");

        for (OneToOne o : aList) {
            
            if (searchType.equalsIgnoreCase(o.getName())) {
                JOptionPane.showMessageDialog(null, "Name: " + o.getName() + "\n Surname: " + o.getSurname() + "\n Email: " + o.getEmail() + "\n Areaofhelp: " + o.getAreaofhelp());
            }
        }
    }//GEN-LAST:event_SearchtfActionPerformed

private void DeletetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletetfActionPerformed
    if (nametf.getText().equals("") || surnametf.getText().equals("") || emailtf.getText().equals("") || areaofhelptf.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "You must enter Name, Surname, Email and Area of Help in order to delete");
    } 
    
    else if (count == 0) {
        JOptionPane.showMessageDialog(null, "Sorry, the file is empty at the moment");
    } 
    
    else {
        name1 = nametf.getText();
        surname = surnametf.getText();
        email1 = emailtf.getText();
        areaofhelp1 = areaofhelptf.getText();

        for (int i = 0; i < aList.size(); i++) {
            
            if (aList.get(i).getName().equals(name1)
                    && aList.get(i).getSurname().equals(surname)
                    && aList.get(i).getEmail().equals(email1)
                    && aList.get(i).getAreaofhelp().equals(areaofhelp1)) {
                aList.remove(i);

                count = count - 1;
                JOptionPane.showMessageDialog(null, "Deleted item at index " + i);
                
                break;
            }
            
            if (i == count - 1) {
                JOptionPane.showMessageDialog(null, "Sorry, Cannot find that item");
            }
        }
    }
}//GEN-LAST:event_DeletetfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneToOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneToOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneToOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneToOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OneToOneGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletetf;
    private javax.swing.JButton Searchtf;
    private javax.swing.JLabel Surname1;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel areaofhelp;
    private javax.swing.JTextField areaofhelptf;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton displaybtn;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtf;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametf;
    private javax.swing.JPanel oneToOnePageJp;
    private javax.swing.JLabel onetoone;
    private javax.swing.JButton readtf;
    private javax.swing.JButton savetf;
    private javax.swing.JTextField surnametf;
    // End of variables declaration//GEN-END:variables
}
