/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Aidan O’ Brien x12117498
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
//The back button image was found on google images and edited in fireworks the link is: http://4.bp.blogspot.com/-hTRk-er3XlY/TZwLBAy9Y6I/AAAAAAAAAQA/upea2uWVG5A/s1600/back_button.jpg
//Picture is sorced from: https//myncistudent.ncirl.ie/StudentServicesAndSupport/StudentSupport/DisabilitySupport/default.aspx
public class QueryMeGUI extends javax.swing.JFrame {

    private ArrayList<QueryMe> info;
    private String sName, mail, qDetails;
    private int count;
    private int sNum;

    /**
     * Creates new form QueryPage
     */
    public QueryMeGUI() {
        initComponents();
        info = new ArrayList<>();
        sName = new String();
        sNum = 0;
        mail = new String();
        qDetails = new String();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundJp = new javax.swing.JPanel();
        HeadingLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        PictureLbl = new javax.swing.JLabel();
        qDetailsJsp = new javax.swing.JScrollPane();
        qDetailsTa = new javax.swing.JTextArea();
        sNameTf = new javax.swing.JTextField();
        sNumTf = new javax.swing.JTextField();
        mailTf = new javax.swing.JTextField();
        StudentNameLbl = new javax.swing.JLabel();
        StudentNumberLbl = new javax.swing.JLabel();
        EMailLbl = new javax.swing.JLabel();
        QueryDetailsLbl = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        SaveInfoBtn = new javax.swing.JButton();
        ViewInfoBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Query");
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        BackgroundJp.setBackground(new java.awt.Color(0, 255, 204));
        BackgroundJp.setMaximumSize(new java.awt.Dimension(320, 480));
        BackgroundJp.setMinimumSize(new java.awt.Dimension(320, 480));
        BackgroundJp.setPreferredSize(new java.awt.Dimension(320, 480));

        HeadingLbl.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        HeadingLbl.setText("Query Page");

        BackBtn.setBackground(new java.awt.Color(0, 255, 204));
        BackBtn.setForeground(new java.awt.Color(0, 255, 204));
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Back.jpg"))); // NOI18N
        BackBtn.setBorder(null);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        PictureLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/reach.jpg"))); // NOI18N
        PictureLbl.setText("jLabel2");

        qDetailsTa.setBackground(new java.awt.Color(255, 255, 204));
        qDetailsTa.setColumns(20);
        qDetailsTa.setRows(5);
        qDetailsJsp.setViewportView(qDetailsTa);

        sNameTf.setBackground(new java.awt.Color(255, 255, 204));
        sNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNameTfActionPerformed(evt);
            }
        });

        sNumTf.setBackground(new java.awt.Color(255, 255, 204));

        mailTf.setBackground(new java.awt.Color(255, 255, 204));

        StudentNameLbl.setText("Student Name");

        StudentNumberLbl.setText("Student Number");

        EMailLbl.setText("e: mail");

        QueryDetailsLbl.setText("Query Details");

        submitBtn.setForeground(new java.awt.Color(0, 0, 204));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        displayBtn.setForeground(new java.awt.Color(0, 0, 204));
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        SaveInfoBtn.setForeground(new java.awt.Color(0, 0, 204));
        SaveInfoBtn.setText("SaveInfo");
        SaveInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveInfoBtnActionPerformed(evt);
            }
        });

        ViewInfoBtn.setForeground(new java.awt.Color(0, 0, 204));
        ViewInfoBtn.setText("ViewInfo");
        ViewInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInfoBtnActionPerformed(evt);
            }
        });

        DelBtn.setForeground(new java.awt.Color(0, 0, 204));
        DelBtn.setText("Delete");
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        SearchBtn.setForeground(new java.awt.Color(0, 0, 204));
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(0, 255, 204));
        homeBtn.setForeground(new java.awt.Color(0, 255, 204));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        homeBtn.setBorder(null);

        javax.swing.GroupLayout BackgroundJpLayout = new javax.swing.GroupLayout(BackgroundJp);
        BackgroundJp.setLayout(BackgroundJpLayout);
        BackgroundJpLayout.setHorizontalGroup(
            BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundJpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundJpLayout.createSequentialGroup()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundJpLayout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qDetailsJsp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QueryDetailsLbl)
                            .addGroup(BackgroundJpLayout.createSequentialGroup()
                                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SaveInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(DelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ViewInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(SearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundJpLayout.createSequentialGroup()
                        .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundJpLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentNumberLbl)
                                    .addComponent(StudentNameLbl)
                                    .addComponent(EMailLbl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundJpLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mailTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(BackgroundJpLayout.createSequentialGroup()
                                .addComponent(HeadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        BackgroundJpLayout.setVerticalGroup(
            BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundJpLayout.createSequentialGroup()
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PictureLbl)
                    .addGroup(BackgroundJpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HeadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentNameLbl)
                    .addComponent(sNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentNumberLbl)
                    .addComponent(sNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMailLbl)
                    .addComponent(mailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(QueryDetailsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qDetailsJsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(displayBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveInfoBtn)
                    .addComponent(ViewInfoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelBtn)
                    .addComponent(SearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(BackgroundJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundJp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(336, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        FirstMeetingGUI myGui = new FirstMeetingGUI();
        myGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void sNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNameTfActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        sName = sNameTf.getText();
        sNum = Integer.parseInt(sNumTf.getText());
        mail = mailTf.getText();
        qDetails = qDetailsTa.getText();

        QueryMe m = new QueryMe();
        m.setsName(sName);
        m.setsNum(sNum);
        m.setMail(mail);
        m.setqDetails(qDetails);

        info.add(m);

        count++;
    }//GEN-LAST:event_submitBtnActionPerformed
    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed

        for (int i = 0; i < info.size(); i++) {
            JOptionPane.showMessageDialog(null, "Student Name: " + info.get(i).getsName() + "\n Student Number: " + info.get(i).getsNum() + "\n Email: " + info.get(i).getMail() + "\n Query: " + info.get(i).getqDetails());

        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void SaveInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveInfoBtnActionPerformed
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("query.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(info);

            JOptionPane.showMessageDialog(null, "File successfully written");

            oStream.close();
        } 
        
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_SaveInfoBtnActionPerformed

    private void ViewInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInfoBtnActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            inFile = new File("query.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);


            ArrayList<QueryMe> xList;
            xList = (ArrayList<QueryMe>) oStream.readObject();
            
            for (QueryMe x : xList) {
                JOptionPane.showMessageDialog(null, "\n S Name: " + x.getsName() + "\n S Num: " + x.getsNum() + "\n e: mail: " + x.getMail() + "\n qDetails: " + x.getqDetails());
            }

            oStream.close();
            
        } 
        
        catch (IOException e) {
            System.out.println(e);
        } 
        
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_ViewInfoBtnActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed
        if (sNameTf.getText().equals("") && sNumTf.getText().equals("") && mailTf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter Student Name, Number and E-mail to delete");
        } 
        
        else if (count == 0) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no items to delete at this time");
        } 
        
        else {
            sName = sNameTf.getText();
            sNum = Integer.parseInt(sNumTf.getText());
            mail = mailTf.getText();


            for (int i = 0; i < info.size(); i++) {
                if (info.get(i).getsName().equals(sName) && info.get(i).getsNum() == sNum && info.get(i).getMail().equals(mail) && info.get(i).getqDetails().equals(qDetails)) {
                    info.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null, "Deleted item at index " + i);
                    break;
                    
                }
                
                if (i == count - 1) {
                    JOptionPane.showMessageDialog(null, "Sorry, that item could not be found");
                }
            }
        }
    }//GEN-LAST:event_DelBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String searchType = JOptionPane.showInputDialog(null, "Please enter the name you wish to search for");

        for (QueryMe x : info) {
            
            if (searchType.equalsIgnoreCase(x.getsName())) {
                JOptionPane.showMessageDialog(null, "\n S Name: " + x.getsName() + "\n S Num: " + x.getsNum() + "\n e: mail: " + x.getMail() + "\n qDetails: " + x.getqDetails());
            }
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;






                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueryMeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueryMeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueryMeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueryMeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueryMeGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel BackgroundJp;
    private javax.swing.JButton DelBtn;
    private javax.swing.JLabel EMailLbl;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JLabel PictureLbl;
    private javax.swing.JLabel QueryDetailsLbl;
    private javax.swing.JButton SaveInfoBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel StudentNameLbl;
    private javax.swing.JLabel StudentNumberLbl;
    private javax.swing.JButton ViewInfoBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JTextField mailTf;
    private javax.swing.JScrollPane qDetailsJsp;
    private javax.swing.JTextArea qDetailsTa;
    private javax.swing.JTextField sNameTf;
    private javax.swing.JTextField sNumTf;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
