/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservicesapp;

/**
 *
 * @author Leon Daly x12112381
 */
//The home button image was found on google images and edited in fireworks the link is: http://images.all-free-download.com/images/graphiclarge/rounded_blue_home_button_4805.jpg
public class SupportOfficerGUI extends javax.swing.JFrame {

    /**
     * Creates new form SupportOfficerGUI
     */
    public SupportOfficerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackjButton1 = new javax.swing.JButton();
        supportOfficerProfileLbl = new javax.swing.JPanel();
        Cal1jButton2 = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        profilejLabel1 = new javax.swing.JLabel();
        namejLabel2 = new javax.swing.JLabel();
        ContactjLabel3 = new javax.swing.JLabel();
        emailjLabel4 = new javax.swing.JLabel();
        NAMEjLabel1 = new javax.swing.JLabel();
        ContactjLabel2 = new javax.swing.JLabel();
        EmailjLabel3 = new javax.swing.JLabel();
        RevisionjButton2 = new javax.swing.JButton();
        OnetoOnejButton2 = new javax.swing.JButton();
        comments = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();
        tutorLbl = new javax.swing.JLabel();

        BackjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BackjButton1.setForeground(new java.awt.Color(0, 0, 204));
        BackjButton1.setText("Back");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Support Officer Profile");
        setBackground(new java.awt.Color(102, 0, 204));
        setMaximumSize(new java.awt.Dimension(320, 480));
        setMinimumSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        supportOfficerProfileLbl.setBackground(new java.awt.Color(0, 255, 204));
        supportOfficerProfileLbl.setForeground(new java.awt.Color(0, 255, 204));
        supportOfficerProfileLbl.setMaximumSize(new java.awt.Dimension(320, 480));
        supportOfficerProfileLbl.setMinimumSize(new java.awt.Dimension(320, 480));
        supportOfficerProfileLbl.setPreferredSize(new java.awt.Dimension(320, 480));

        Cal1jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cal1jButton2.setForeground(new java.awt.Color(0, 0, 204));
        Cal1jButton2.setText("Go to Calculator");
        Cal1jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cal1jButton2ActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(0, 255, 204));
        Home.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 255, 204));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Home.jpg"))); // NOI18N
        Home.setBorder(null);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        profilejLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        profilejLabel1.setText("Support Officer Profile");

        namejLabel2.setText("Name :");

        ContactjLabel3.setText("Contact :");

        emailjLabel4.setText("Email :");

        NAMEjLabel1.setBackground(new java.awt.Color(0, 0, 0));
        NAMEjLabel1.setText("Jonathan Lambert");

        ContactjLabel2.setBackground(new java.awt.Color(0, 0, 0));
        ContactjLabel2.setText("01 4498650");

        EmailjLabel3.setBackground(new java.awt.Color(0, 0, 0));
        EmailjLabel3.setText("jonathan.lambert@gmail.com");

        RevisionjButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RevisionjButton2.setForeground(new java.awt.Color(0, 0, 204));
        RevisionjButton2.setText("Exam Revision");
        RevisionjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevisionjButton2ActionPerformed(evt);
            }
        });

        OnetoOnejButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OnetoOnejButton2.setForeground(new java.awt.Color(0, 0, 204));
        OnetoOnejButton2.setText("  OneToOne Help");
        OnetoOnejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnetoOnejButton2ActionPerformed(evt);
            }
        });

        comments.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comments.setForeground(new java.awt.Color(0, 0, 204));
        comments.setText("Comments And Feedback");
        comments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentsActionPerformed(evt);
            }
        });

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/nci logo_1.jpg"))); // NOI18N

        tutorLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservicesapp/Johnaton.gif"))); // NOI18N
        tutorLbl.setText("jLabel2");

        javax.swing.GroupLayout supportOfficerProfileLblLayout = new javax.swing.GroupLayout(supportOfficerProfileLbl);
        supportOfficerProfileLbl.setLayout(supportOfficerProfileLblLayout);
        supportOfficerProfileLblLayout.setHorizontalGroup(
            supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supportOfficerProfileLblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cal1jButton2)
                .addGap(18, 18, 18))
            .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(profilejLabel1))
                    .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RevisionjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(OnetoOnejButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(comments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supportOfficerProfileLblLayout.createSequentialGroup()
                .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Home))
                    .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                                .addComponent(emailjLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailjLabel3))
                            .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                                .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContactjLabel3)
                                    .addComponent(namejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContactjLabel2)
                                    .addComponent(NAMEjLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tutorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        supportOfficerProfileLblLayout.setVerticalGroup(
            supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, supportOfficerProfileLblLayout.createSequentialGroup()
                .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Cal1jButton2))
                    .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(profilejLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supportOfficerProfileLblLayout.createSequentialGroup()
                        .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejLabel2)
                            .addComponent(NAMEjLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactjLabel2)
                            .addComponent(ContactjLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(supportOfficerProfileLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjLabel4)
                            .addComponent(EmailjLabel3)))
                    .addComponent(tutorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(OnetoOnejButton2)
                .addGap(18, 18, 18)
                .addComponent(RevisionjButton2)
                .addGap(18, 18, 18)
                .addComponent(comments)
                .addGap(30, 30, 30)
                .addComponent(Home)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supportOfficerProfileLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supportOfficerProfileLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(336, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cal1jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cal1jButton2ActionPerformed
        mathsGui myGui = new mathsGui();
        myGui.setVisible(true);  
        this.setVisible(false); 
    }//GEN-LAST:event_Cal1jButton2ActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        StudentServicesAppGUI myGui = new StudentServicesAppGUI();
        myGui.setVisible(true); 
        this.setVisible(false);   
    }//GEN-LAST:event_HomeActionPerformed

    private void RevisionjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevisionjButton2ActionPerformed
        ExamRevisionGUI myGui = new ExamRevisionGUI();
        myGui.setVisible(true); 
        this.setVisible(false);   
    }//GEN-LAST:event_RevisionjButton2ActionPerformed

    private void OnetoOnejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnetoOnejButton2ActionPerformed
        OneToOneGUI myGui = new OneToOneGUI();
        myGui.setVisible(true); 
        this.setVisible(false);   
    }//GEN-LAST:event_OnetoOnejButton2ActionPerformed

    private void commentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsActionPerformed
        CommonspageGUI myGui = new CommonspageGUI();
        myGui.setVisible(true); 
        this.setVisible(false);   
    }//GEN-LAST:event_commentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupportOfficerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupportOfficerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupportOfficerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupportOfficerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupportOfficerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackjButton1;
    private javax.swing.JButton Cal1jButton2;
    private javax.swing.JLabel ContactjLabel2;
    private javax.swing.JLabel ContactjLabel3;
    private javax.swing.JLabel EmailjLabel3;
    private javax.swing.JButton Home;
    private javax.swing.JLabel NAMEjLabel1;
    private javax.swing.JButton OnetoOnejButton2;
    private javax.swing.JButton RevisionjButton2;
    private javax.swing.JButton comments;
    private javax.swing.JLabel emailjLabel4;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel namejLabel2;
    private javax.swing.JLabel profilejLabel1;
    private javax.swing.JPanel supportOfficerProfileLbl;
    private javax.swing.JLabel tutorLbl;
    // End of variables declaration//GEN-END:variables
}
